baseURL = "https://raydwaipayan.github.io/blogs"
canonifyURLs = true
languageCode = "en-us"
title = "Dwai's blogs"
theme = "papermod"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
